sudo: required
services:
  - docker

before_install:
  - chmod +x build.sh
  - docker build -t rynohoopty/docker-react -f Dockerfile.dev .

script:
  - docker run rynohoopty/docker-react npm run test -- --coverage
  